name: todoapp Workflow
run-name: triggered by ${{ github.actor }} for ${{ github.sha }}

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  python_v: 3.12

jobs:
  python-ci:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_v }}

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
